#!/bin/sh
#
# Simple script to package GIMP Book for publishing.

files="book.py docs license.txt locale icons"
echo "Preparing the followign files and folders for publishing:"
echo $files

v="1.0.0"

sed -i "s/current_version/$v/g" book.py
sed -i "s/current_version/$v/g" docs/index.html


if [ ! -d publish ]
then
    mkdir publish
fi
# Make all languages
cd locale
for f in `ls -1 *.po`
do
    translation_language=`echo $f | cut -d . -f 1`
    echo "Compiling translation for $translation_language"
    mkdir -p $translation_language/LC_MESSAGES
    msgfmt $translation_language.po --output-file $translation_language/LC_MESSAGES/book.mo
done
cd ..
zip -r "publish/gimp_book_$v.zip" $files -x *.svn*
sed -i "s/$v/current_version/g" book.py
sed -i "s/$v/current_version/g" docs/index.html

echo "New version saved to publish/Gimp Book - $v.zip"
