#!/bin/sh
#
# Simple script to package GIMP Book for publishing.

files="book.py docs license.txt"
echo "Preparing the followign files and folders for publishing:"
echo $files

version=`date +%Y.%-m` 
revision=`svn info http://svn.ragtag.net/gimp | grep Revision | cut -d\  -f 2`
v="$version rev $revision"

mv book.py book.py.bak
mv docs/index.html index.html
cat book.py.bak | sed "s/current_version/$v/" > book.py
cat index.html | sed "s/current_version/$v/" > docs/index.html


if [ ! -d publish ]
then
    mkdir publish
fi
zip -r "publish/Gimp Book - $v.zip" $files -x *.svn*
mv book.py.bak book.py
mv index.html docs/index.html

echo "New version saved to publish/Gimp Book - $v.zip"
